### ISSUE TITLE
Question/Request tfvars format

### ISSUE THREAD

**Issue by voltechs** [tmichel/sublime-terraform#5]
Any reason why you're not formatting `tfvars`? I didn't see an explanation in the commit for this.

REF: https://github.com/tmichel/sublime-terraform/commit/84ae20fce4956b564b1a340fa0bba2bab43621c5#commitcomment-35045219

**Comment by tmichel** [comment]
I think this was a subjective style decisions because I did not want aligned variable declarations in my `tfvars` files. There is no particular technical reason behind it. 

I don't remember why I removed the option to configure this. Probably there was some bug around formatting and at that time I was the only user of this plugin so the configuration was unnecessary.
